apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: controllers
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::783479263698:role/bedrock-external-secrets-role
