# External Secrets Operator values
replicaCount: 1

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "${AWS_ROLE_ARN}"  # This will be replaced with the actual role ARN

securityContext:
  enabled: true

webhook:
  create: true

certController:
  create: true
